version: '3.0'

expectations:
  population_size: 1000

actions:

  extract:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition
    outputs:
      highly_sensitive:
        cohort: output/input.feather
