version: '3.0'

expectations:
  population_size: 10000

actions:

  extract_fixed:
    run: ehrql:v0 generate-dataset analysis/dataset_definition_fixed.py
      --output output/extracts/extract_fixed.arrow
      --dummy-data-file lib/dummydata/dummyinput_fixed.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_fixed.arrow

  extract_varying:
    run: ehrql:v0 generate-dataset analysis/dataset_definition_varying.py
      --output output/extracts/extract_varying.arrow
      --dummy-data-file lib/dummydata/dummyinput_varying.arrow
    outputs:
      highly_sensitive:
        cohort: output/extracts/extract_varying.arrow


  process:
    run: r:latest analysis/process.R
    needs: [extract_fixed, extract_varying]
    outputs:
      highly_sensitive:
        rds: output/process/*.rds

  report:
    run: r:latest analysis/report.R
    needs: [process]
    outputs:
      moderately_sensitive:
        csv: output/report/*.csv
        png: output/report/*.png

  # Additional actions for snapshot
  extract_snapshot:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_snapshot
        --skip-existing
        --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_snapshot.csv.gz

  process_snapshot:
    run: r:latest analysis/snapshot_process.R
    needs: [extract_snapshot]
    outputs:
      highly_sensitive:
        rds: output/snapshot/processed_snapshot.rds

  report_snapshot:
    run: r:latest analysis/snapshot_report.R
    needs: [process_snapshot]
    outputs:
      highly_sensitive:
        rds: output/snapshot_report/snapshot_summary.rds
      moderately_sensitive:
        csv: output/snapshot_report/snapshot_summary.csv
    
  html_snapshot:
    run: r:latest -e 'rmarkdown::render("analysis/vaccine_snapshot_report.Rmd", knit_root_dir = "/workspace", output_dir="/workspace/output/snapshot_report")'
    needs: [process_snapshot, report_snapshot]
    outputs:
      moderately_sensitive:
        html: output/snapshot_report/vaccine_snapshot_report.html
        png: output/snapshot_report/*.png
