version: '3.0'

expectations:
  population_size: 1000

actions:

  extract_fixed:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition_fixed
    outputs:
      highly_sensitive:
        cohort: output/input_fixed.feather

  extract_varying:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition_varying
    outputs:
      highly_sensitive:
        cohort: output/input_varying.feather


  process:
    run: r:latest analysis/process.R
    needs: [extract_fixed, extract_varying]
    outputs:
      highly_sensitive:
        rds: output/process/*.rds

  report:
    run: r:latest analysis/report.R
    needs: [process]
    outputs:
      moderately_sensitive:
        csv: output/report/*.csv
        png: output/report/*.png

  # Additional actions for snapshot
  extract_snaphot:
    run: >
      cohortextractor:latest generate_cohort
        --study-definition study_definition_snapshot
        --skip-existing
        --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_snapshot.csv.gz
        
  process_snapshot:
    run: r:latest analysis/snapshot_process.R
    needs: [extract_snaphot]
    outputs:
      highly_sensitive:
        rds: output/snapshot/processed_snapshot.rds

  report_snapshot:
    run: r:latest analysis/snapshot_report.R
    needs: [process_snapshot]
    outputs:
      moderately_sensitive:
        csv: output/snapshot_report/snapshot*.csv
