version: '3.0'

expectations:
  population_size: 1000

actions:

  extract_fixed:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition_fixed
    outputs:
      highly_sensitive:
        cohort: output/input_fixed.feather

  extract_varying:
    run: cohortextractor:latest generate_cohort --output-format feather --study-definition study_definition_varying
    outputs:
      highly_sensitive:
        cohort: output/input_varying.feather


  process:
    run: r:latest analysis/process.R
    needs: [extract_fixed, extract_varying]
    outputs:
      highly_sensitive:
        rds: output/process/*.rds

  report:
    run: r:latest analysis/report.R
    needs: [process]
    outputs:
      moderately_sensitive:
        csv: output/report/*.csv
        png: output/report/*.png
